### PR TITLE
Split nurse in Fem/Masc + Spanish fixes

### PR DESCRIPTION
**Pull request by inariksit**

### CODE REVIEW

**Comment by krangelov** [comment]
Btw. I wouldn't spend time to improve these dictionaries any more. The
WordNet is supposed to replace them so any further improvements here will
be lost.


На ср, 13.02.2019 г., 15:01 Inari Listenmaa <notifications@github.com
написа:

**Comment by inariksit** [comment]
@krangelov I see. I'm revising these entries because I'm adding Spanish words to our obstetrics grammar, and I thought it's better to fix things in some more global resource than just in one application grammar. There's no Spanish yet in the WordNet grammar/lexicon, what should I do to get Spanish in there?

**Comment by inariksit** [comment]
Okay I found it, I'll use this https://github.com/GrammaticalFramework/gf-wordnet/tree/master/bootstrap .

**Comment by krangelov** [comment]
In that folder there is a file mapping.txt which maps the abstract syntax
of the old dictionaries to the WordNet syntax. However, this is not all
that is needed since the old dictionaries are really really bad.

It is better to start porting the Spannish WordNet and to use DictionarySpa
only when there is nothing better.

I don't mean that you should start building Spannish WordNet right now but
just don't spend too much time for small fixes in the old stuff.

**Comment by inariksit** [comment]
Alright. I can create a monolingual DictSpa out of the old DictionarySpa, where I can do all the fixes I want, and then you can create WordNetSpa in the way you like best. Or do you think it's better to just create it from scratch from WordNet?

**Comment by krangelov** [comment]
DictSpa sounds good.

На чт, 14.02.2019 г., 16:00 Inari Listenmaa <notifications@github.com
написа:

**Comment by inariksit** [comment]
Ok, I'll do that and then we can populate a WordNetSpa eventually.

**Comment by inariksit** [comment]
https://github.com/GrammaticalFramework/gf-rgl/pull/175 I have added DictSpa, based on DictionarySpa and http://compling.hss.ntu.edu.sg/omw/ .

**Pull request merged**
